import { MouseInterface, XY } from '../../types/interfaces';
import { Axis, Direction } from '../../types/types';
import { CircleBoundary, RectBoundary } from './boundaries';
import Bullet from './Bullet';
import Entity from './Entity';
import Polygon from './Polygon';
declare type DecelerateScalars = Record<Axis, number>;
export default class Spaceship extends Entity {
    angle: number;
    shotAvailable: boolean;
    bullets: Bullet[];
    decelerateScalars: DecelerateScalars;
    readonly ACCELERATION_RATE: number;
    accelerating: boolean;
    readonly MAX_SPEED: number;
    velocity: XY;
    readonly IMAGE: HTMLImageElement;
    readonly CONVEX_POLYGONS: Polygon[];
    readonly BOUNDING_BOX: Polygon;
    colliding: boolean;
    constructor({ x, y }: XY, theme: 'dark' | 'light', speed: number);
    move(dir: Direction): void;
    handleBoundsCollision(bounds: XY): void;
    handleCollisionWithCircle(boundary: CircleBoundary): void;
    handleCollisionWithRect(boundary: RectBoundary): void;
    updateXPosition(shift?: number): void;
    updateYPosition(shift?: number): void;
    shoot(): void;
    getCenter(): XY;
    draw(c: CanvasRenderingContext2D): void;
    drawFlames(c: CanvasRenderingContext2D): void;
    alignToMouse(mouse: MouseInterface): void;
    resetDeceleration(axis: Axis): void;
    decelerate(axis: Axis): void;
    removeBullet(i: number): void;
    getVerticesBoundingBox(): XY[];
    getPolygons(): Polygon[];
}
export {};
